### ISSUE TITLE
Modal is too big in mobile screen

### ISSUE THREAD

**Issue by devbytemehedi** [devbytemehedi/shopwave#2]
### use tailwind class to fix the issue

**Comment by Bolaji06** [comment]
Hello @devbytemehedi, Can you assign me to this issue?

**Comment by Bolaji06** [comment]
Hope this satisfy your requirement
<img width="311" alt="shop" src="https://github.com/devbytemehedi/shopwave/assets/40664855/26edaaf3-a901-4d6f-a17f-990f5b4e08ee">

**Comment by Bolaji06** [comment]
Sending PR soon

**Comment by devbytemehedi** [comment]
@Bolaji06 Great work. Keep up the good work.

**Comment by Bolaji06** [comment]
> @Bolaji06 Great work. Keep up the good work.

Glad I could provide value to your project and thanks for allowing me to work on the project. Appreciate.
