### ISSUE TITLE
Social link icons are too small in mobile screen

### ISSUE THREAD

**Issue by devbytemehedi** [devbytemehedi/shopwave#4]
### ⚙️ Issue Title

Social link Icons are too small in mobile screen

### ℹ️ Issue Description

if you open the [website](https://devbytemehedi.github.io/shopwave) on a mobile device you will see that **social link icons** on footer in mobile screen is too small.

### Expected Behavior

icons should be `30px` on `small` and `medium` device

### Actual Behavior (📷)
![ss](https://github.com/devbytemehedi/shopwave/assets/89072438/ed94e8b7-9fd6-4ea0-94c6-bdc88b444d43)

### 📘 Contribution Guidelines

Please make sure to read [README.md](https://github.com/devbytemehedi/shopwave/blob/main/README.md) to run the project  and  [Contribution Guidelines](https://github.com/devbytemehedi/shopwave/blob/main/CONTRIBUTION.md) before submitting your contribution.

🤔 If you have any questions or need further assistance, feel free to ask on this issue.

### 💡 Tips
- Keep your changes focused and small.
- If you need help, don't hesitate to ask questions in the comments.

---

**Comment by goodylove** [comment]
I am interested to fix the issue

**Comment by devbytemehedi** [comment]
@goodylove good luck.

**Comment by goodylove** [comment]
please review my PR

**Comment by devbytemehedi** [comment]
@goodylove remove extra class `md:text-3xl` and i will merge it

**Comment by devbytemehedi** [comment]
@goodylove good work. keep it up.
