### ISSUE TITLE
add click to copy event to the coupon-code button

### ISSUE THREAD

**Issue by devbytemehedi** [devbytemehedi/shopwave#6]
### ⚙️ Issue Title

 there is no  click to copy event to the coupon-code button

### ℹ️ Issue Description

If you go to the live [website](https://dub.sh/shopwave) you will see a button in header call `SELL200` which is coupon code

### Expected Behavior

If you click the button or touch the button on any device coupon code innerText should be copied to clipboard.

### Actual Behavior (📷)

Currently after clicking the button nothing is happening.

### 📘 Contribution Guidelines

Please make sure to read our [Contribution Guidelines](https://github.com/devbytemehedi/shopwave/blob/main/CONTRIBUTION.md) before submitting your contribution.

🤔 If you have any questions or need further assistance, feel free to ask on this issue.

Thank you for contributing!

### 💡 Tips

- Keep your changes focused and small.
- If you need help, don't hesitate to ask questions in the comments.

---

**Comment by AbhiramMngi** [comment]
Hi, I would like to take this one as my first contribution, could you please kindly assign this to me?

**Comment by devbytemehedi** [comment]
@AbhiramMngi good luck.

**Comment by AbhiramMngi** [comment]
The contribution guidelines page seems to be not working, can you give me another link?

**Comment by devbytemehedi** [comment]
@AbhiramMngi https://github.com/devbytemehedi/shopwave/blob/main/CONTRIBUTION.md

**Comment by AbhiramMngi** [comment]
can you check my pr?, I've verified it and it's working.

**Comment by devbytemehedi** [comment]
@AbhiramMngi Good job. Kepp it up.
